# - Problem 29
# - Distinct Powers
# 
# How many distinct terms are in the sequence generated by a^b

n = 100

ist= []
for a in range(2, n+1):
	for b in range(2, n+1):
		ist.append(a**b)
	
print(len(set(ist)))