# - Problem 44
# - Pentagon Numbers
# 
# Pentagonal numbers are generated by the formula, Pn = n(3n-1)/2.
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = abs(Pk-Pj) is minimised;
# what is the value of D?

from math import sqrt

def isPentagonal(x):
	return (sqrt(1 + 24 * x) % 6) == 5

def P (n):
	return n * (3 * n - 1) / 2

n = 5000
mn = float("inf")

for i in range(1,n):
	Pi = P(i)
	for j in range(i+1, n):
		Pj = P(j)
		d = abs(Pi-Pj)
		if isPentagonal(d) and isPentagonal(Pi+Pj):
			if d < mn:
				mn = d

print(mn)